name: Static analysis

on: [push, pull_request]

jobs:
  run:
    if: ${{ !startsWith(github.event.head_commit.message, 'Translation:') }}
    runs-on: ${{ matrix.operating-system }}
    name: phpstan

    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest' ]
        php-version: [ '7.4', '8.0', '8.1', '8.2', '8.3', '8.4' ]
      fail-fast: false

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - uses: actions/checkout@v4

      - run: composer validate

      - run: composer install --no-progress

      - run: composer webtrees:phpcs
